(()=>{
'use strict';
if(!window.FixtureExcel){const el=document.getElementById('message');el.textContent='Excel 组件未加载。请完整解压源码包后打开 index.html，或刷新在线网页。';el.classList.add('error');return;}
const{readWorkbook,detect,records,matchRows,exportColumn,exportColumns,colName}=window.FixtureExcel;
const $=id=>document.getElementById(id);let source,target,sourceSheet,targetSheet,sourceCfg,targetCfg,sourceRows=[],results=[];const versions={source:0,target:0};
function message(s,error=false){$('message').textContent=s;$('message').classList.toggle('error',error)}
function invalidate(){results=[];$('results').hidden=true;$('empty').hidden=false;$('match').disabled=!(source&&target)}
function setSheet(kind){const b=kind==='source'?source:target,sel=$(kind+'Sheet'),s=b.sheets[+sel.value];if(kind==='source')sourceSheet=s;else targetSheet=s;invalidate();message(source&&target?'两份文件已就绪，点击「开始匹配」。':'请继续选择另一份 Excel。')}
async function load(kind,file){if(!file)return;const version=++versions[kind];if(kind==='source')source=null;else target=null;invalidate();$(kind+'Sheet').disabled=true;$(kind+'Label').textContent='正在读取…';message('正在读取 Excel…');try{const b=await readWorkbook(file);if(version!==versions[kind])return;if(kind==='source')source=b;else target=b;const sel=$(kind+'Sheet');sel.replaceChildren(...b.sheets.map((s,i)=>new Option(s.name,i)));const found=b.sheets.findIndex(s=>{try{detect(s,kind);return true}catch{return false}});sel.value=String(Math.max(found,0));sel.disabled=false;$(kind+'Label').textContent=file.name;setSheet(kind)}catch(e){if(version!==versions[kind])return;$(kind+'Label').textContent='重新选择 Excel';message(e.message,true)}}
for(const kind of ['source','target']){
 const input=$(kind+'File'),box=input.closest('.filebox');let depth=0;
 input.addEventListener('click',()=>{input.value=''});
 input.addEventListener('change',e=>load(kind,e.target.files[0]));
 $(kind+'Sheet').addEventListener('change',()=>setSheet(kind));
 box.addEventListener('dragenter',e=>{e.preventDefault();e.stopPropagation();depth++;box.classList.add('dragover')});
 box.addEventListener('dragover',e=>{e.preventDefault();e.stopPropagation();if(e.dataTransfer)e.dataTransfer.dropEffect='copy'});
 box.addEventListener('dragleave',e=>{e.preventDefault();e.stopPropagation();depth=Math.max(0,depth-1);if(!depth)box.classList.remove('dragover')});
 box.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();depth=0;box.classList.remove('dragover');const files=Array.from(e.dataTransfer?.files??[]);if(files.length!==1){message('每个区域一次请放入一份 Excel 文件。',true);return;}load(kind,files[0])});
}
window.addEventListener('dragover',e=>{if(Array.from(e.dataTransfer?.types??[]).includes('Files'))e.preventDefault()});
window.addEventListener('drop',e=>{if(Array.from(e.dataTransfer?.types??[]).includes('Files')){e.preventDefault();document.querySelectorAll('.dragover').forEach(el=>el.classList.remove('dragover'));message('请将文件拖到对应的流程统计表或申请审核表区域。',true)}});
window.addEventListener('dragend',()=>document.querySelectorAll('.dragover').forEach(el=>el.classList.remove('dragover')));
message('请点击选择或拖入两份 Excel 文件。原文件不会被修改。');
window.fixtureAppReady=true;

function people(r){const c=r.selected===null?null:r.candidates[r.selected];return{requester:String(r.requester||c?.requester||'').trim(),designer:String(r.designer||c?.designer||'').trim()}}
function personMapping(cfg,label){const out=[];if(cfg.requesterCol)out.push(`需求人 ${colName(cfg.requesterCol)}列`);if(cfg.designerCol)out.push(`设计人 ${colName(cfg.designerCol)}列`);return out.length?`${label}${out.join(' / ')}`:''}
function run(){if(!source||!target)throw Error('请先选择两份 Excel');sourceCfg=detect(sourceSheet,'source');targetCfg=detect(targetSheet,'target');sourceRows=records(sourceSheet,sourceCfg);const ts=records(targetSheet,targetCfg);if(!sourceRows.length||!ts.length)throw Error('选择的工作表没有可匹配的数据');results=matchRows(ts,sourceRows);$('results').hidden=false;$('empty').hidden=true;const personInfo=[personMapping(targetCfg,'审核表：'),personMapping(sourceCfg,'流程表：')].filter(Boolean).join('；');$('mapping').textContent=`来源 ${colName(sourceCfg.codeCol)} 列 + ${colName(sourceCfg.nameCol)} 列 → 审核表 ${colName(targetCfg.nameCol)} 列名称${personInfo?'；'+personInfo:'；未识别到人员表头，需求人/设计人将留空'}`;message(`已读取 ${sourceRows.length} 条流程记录，核对 ${results.length} 条审核项目。${sourceCfg.fallback?'未识别到标准标题，当前使用 X / AP 列，请核对。':''}`);render();return summary()}
function summary(){return{total:results.length,matched:results.filter(r=>r.selected!==null).length,ambiguous:results.filter(r=>r.status==='ambiguous'&&r.selected===null).length,missing:results.filter(r=>!r.candidates.length).length}}
$('match').onclick=()=>{try{run()}catch(e){message(e.message,true)}};
function appendTextCell(tr,value,empty='—'){const td=document.createElement('td');td.textContent=value||empty;tr.append(td)}
function render(){const counts=summary();for(const[k,v]of Object.entries(counts))$(k).textContent=v;const search=$('search').value.toLowerCase(),filter=$('filter').value;$('rows').replaceChildren();for(const r of results){const done=r.selected!==null,p=people(r),haystack=`${r.name} ${p.requester} ${p.designer} ${r.candidates.map(c=>`${c.code} ${c.requester} ${c.designer}`).join(' ')}`.toLowerCase();if(filter==='todo'&&done||filter==='done'&&!done)continue;if(search&&!haystack.includes(search))continue;const tr=document.createElement('tr');appendTextCell(tr,String(r.row),'');appendTextCell(tr,r.name,'');appendTextCell(tr,r.quantity===null?'—':String(r.quantity),'—');appendTextCell(tr,p.requester);appendTextCell(tr,p.designer);const st=document.createElement('td'),badge=document.createElement('span');badge.className='badge'+(!done?(r.candidates.length?' todo':' miss'):'');badge.textContent=done?(r.reason==='quantity'?'数量匹配':r.reason==='alias'?'近似名称匹配':r.reason==='suffix'?'名称简写匹配':r.status==='ambiguous'?'已确认':'已匹配'):r.status==='ambiguous'?'同名待确认':r.status==='noCode'?'来源无编码':'未找到';st.append(badge);tr.append(st);const value=document.createElement('td');if(done){const c=r.candidates[r.selected];const line=document.createElement('div');line.textContent=c.code+' '+c.name;value.append(line);const note=document.createElement('small');const who=[c.requester&&`需求人：${c.requester}`,c.designer&&`设计人：${c.designer}`].filter(Boolean).join(' · ');note.textContent=`流程表第 ${c.rows.join('、')} 行 · 编码个数：${c.count??'无法识别'}${r.reason==='quantity'?`，与审核数量 ${r.quantity} 一致`:''}${r.quantity!==null&&c.count!==null&&r.quantity!==c.count?` · ⚠ 审核数量 ${r.quantity} 与编码个数 ${c.count} 不同`:''}${who?' · '+who:''}`;value.append(note)}else if(!r.candidates.length)value.textContent=r.status==='noCode'?'名称可匹配，但流程表编码为空。':'流程表没有找到可匹配的名称。';if(r.candidates.length>1){const sel=document.createElement('select');sel.className='candidate';sel.setAttribute('aria-label',`审核表第 ${r.row} 行选择编码`);sel.append(new Option('请选择对应编码（未选时编码、人名按可用信息导出）',''));r.candidates.forEach((c,i)=>{const who=[c.requester,c.designer].filter(Boolean).join(' / ');sel.append(new Option(`第 ${c.rows.join('、')} 行 · ${c.count===null?'个数无法识别':c.count+' 个编码'} · ${c.code} ${c.name}${who?' · '+who:''}`,i))});sel.value=r.selected===null?'':String(r.selected);sel.onchange=()=>{r.selected=sel.value===''?null:+sel.value;r.reason=r.selected===null?null:'manual';render()};value.append(sel)}tr.append(value);$('rows').append(tr)}if(!$('rows').children.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=7;td.textContent='没有符合条件的项目。';tr.append(td);$('rows').append(tr)}}
$('filter').onchange=render;$('search').oninput=render;
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
$('exportTarget').onclick=()=>{try{const codeValues=[],requesterValues=[],designerValues=[];for(const r of results){const p=people(r),code=r.selected===null?'':r.candidates[r.selected].code+' '+r.candidates[r.selected].name;codeValues.push([r.row,code]);requesterValues.push([r.row,p.requester]);designerValues.push([r.row,p.designer])}download(exportColumns(target,targetSheet,targetCfg,[{header:'编码+名称',values:codeValues,width:78},{header:'需求人',values:requesterValues,width:18},{header:'设计人',values:designerValues,width:18}]),target.name.replace(/\.xlsx$/i,'_编码人员匹配.xlsx'));const n=results.filter(r=>r.selected===null).length;message(`已导出审核结果，并新增「编码+名称 / 需求人 / 设计人」。${n?`${n} 个未确认或未找到的项目编码保留空白。`:'所有项目均已填入编码。'}`)}catch(e){message(e.message,true)}};
$('exportSource').onclick=()=>{try{download(exportColumn(source,sourceSheet,sourceCfg,sourceRows.map(r=>[r.row,r.code+' '+r.name]),'编码+名称',true),source.name.replace(/\.xlsx$/i,'_编码名称.xlsx'));message('已导出流程拼接表，在末尾添加「编码+名称」。')}catch(e){message(e.message,true)}};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'match_uploaded_workbooks',description:'对用户已选择的两份 Excel 执行完整名称匹配，并显示结果；不导出文件。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');return run()}})).catch(()=>{})}catch{}}
})();
